CREATE TABLE IF NOT EXISTS `#__ufWidget` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`script` text NOT NULL,
	`lang` VARCHAR(25) NOT NULL,

  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;